### ISSUE TITLE
admin controllers

### ISSUE THREAD

**Issue by ghost** [spree-contrib/spree_paypal_express#10]
hi,
can you confirm there is currently no admin interface to do captures and void of order payments? I can see the routes for it:
capture_admin_order_paypal_payment GET      /admin/orders/:order_id/paypal_payments/:id/capture(.:format) {:action=>"capture", :controller=>"admin/paypal_payments"}
but no controller in the extension.
Ta,
Enrico

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
