### ISSUE TITLE
undefined method `addresses'

### ISSUE THREAD

**Issue by bigbentobox** [spree-contrib/spree_paypal_express#101]
When I want to do payment with PayPal on the master branch of spree I get this error : 

```
 Started GET "/orders/R605881368/checkout/paypal_payment?payment_method_id=1" for 81.83.15.153 at 2012-11-21 17:15:41 +0100
 Processing by Spree::CheckoutController#paypal_payment as HTML
 Parameters: {"payment_method_id"=>"1", "order_id"=>"R605881368"}
 Completed 500 Internal Server Error in 128ms

 NoMethodError (undefined method `addresses' for #<Spree::User:0x00000008371268>):
 activemodel (3.2.8) lib/active_model/attribute_methods.rb:407:in `method_missing'
```

What is wrong?

**Comment by JDutil** [comment]
This should be fixed once you update to the latest commit. i.e.

```
$ bundle update spree_paypal_express
```

Then restart your web server.

**Comment by bozza70** [comment]
Hi Am not sure if this is the same problem..I update to the latest commit and I get the following error.

Started PUT "/checkout/update/payment" for 127.0.0.1 at 2012-11-27 09:45:14 +1100
Processing by Spree::CheckoutController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"yEWk+Xnypg7P60EQuembhf7/SK9NH2f9z91uHBk3B0U=", "order"=>{"payments_attributes"=>[{"payment_method_id"=>"1"}]}, "state"=>"payment"}
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/allow_ssl_in_development_and_test' LIMIT 1
  Spree::Preference Exists (0.2ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/default_locale' LIMIT 1
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'default_locale' LIMIT 1
  CACHE (0.0ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/default_locale' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'default_locale' LIMIT 1
  Spree::User Load (0.3ms)  SELECT "spree_users".\* FROM "spree_users" WHERE "spree_users"."id" = 1 LIMIT 1
  Spree::Order Load (0.3ms)  SELECT "spree_orders".\* FROM "spree_orders" WHERE "spree_orders"."user_id" = 1 AND "spree_orders"."completed_at" IS NULL ORDER BY created_at ASC LIMIT 1
  Spree::Order Load (0.2ms)  SELECT "spree_orders".\* FROM "spree_orders" WHERE "spree_orders"."id" = 3 LIMIT 1
  Spree::Adjustment Load (0.3ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."adjustable_id" IN (3) ORDER BY created_at ASC
   (0.1ms)  SELECT COUNT(_) FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  Spree::LineItem Load (0.1ms)  SELECT "spree_line_items"._ FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/allow_backorders' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'allow_backorders' LIMIT 1
  Spree::Payment Load (0.1ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3
  Spree::Payment Load (0.2ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 AND "spree_payments"."state" = 'completed'
  Spree::Adjustment Load (0.3ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  Spree::PaymentMethod Load (0.2ms)  SELECT "spree_payment_methods".\* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/billing_integration/paypal_express/review/1' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_users".\* FROM "spree_users" WHERE "spree_users"."id" = 1 LIMIT 1
   (0.2ms)  SELECT COUNT(_) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = 1 AND "spree_roles"."name" = 'admin'
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/auth_configuration/registration_step' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences"._ FROM "spree_preferences" WHERE "spree_preferences"."name" = 'registration_step' LIMIT 1
   (0.0ms)  begin transaction
  CACHE (0.0ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 AND "spree_payments"."state" = 'completed'
  CACHE (0.0ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  Spree::PaymentMethod Load (0.3ms)  SELECT "spree_payment_methods".\* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = 1 LIMIT 1
  CACHE (0.0ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/billing_integration/paypal_express/review/1' LIMIT 1
  Spree::Order Exists (0.1ms)  SELECT 1 AS one FROM "spree_orders" WHERE ("spree_orders"."number" = 'R823341561' AND "spree_orders"."id" != 3) LIMIT 1
  SQL (0.3ms)  INSERT INTO "spree_payments" ("amount", "avs_response", "created_at", "order_id", "payment_method_id", "response_code", "source_id", "source_type", "state", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["amount", #<BigDecimal:ca1b90c,'0.3399E2',18(36)>], ["avs_response", nil], ["created_at", Mon, 26 Nov 2012 22:45:14 UTC +00:00], ["order_id", 3], ["payment_method_id", 1], ["response_code", nil], ["source_id", nil], ["source_type", nil], ["state", "checkout"], ["updated_at", Mon, 26 Nov 2012 22:45:14 UTC +00:00]]
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/billing_integration/paypal_express/review/1' LIMIT 1
  Spree::Order Load (0.2ms)  SELECT "spree_orders".\* FROM "spree_orders" WHERE "spree_orders"."id" = 3 LIMIT 1
  Spree::Payment Load (0.1ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3
  Spree::Payment Load (0.1ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 AND "spree_payments"."state" = 'completed'
  Spree::LineItem Load (0.1ms)  SELECT "spree_line_items".\* FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  Spree::Adjustment Load (0.3ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  Spree::Shipment Load (0.2ms)  SELECT "spree_shipments".\* FROM "spree_shipments" WHERE "spree_shipments"."order_id" = 3
  SQL (0.1ms)  UPDATE "spree_shipments" SET "state" = 'pending' WHERE "spree_shipments"."id" = 3
   (0.1ms)  SELECT COUNT(_) FROM "spree_shipments" WHERE "spree_shipments"."order_id" = 3
   (0.1ms)  SELECT COUNT(_) FROM "spree_shipments" WHERE "spree_shipments"."order_id" = 3 AND "spree_shipments"."state" = 'shipped'
   (0.1ms)  SELECT COUNT(_) FROM "spree_shipments" WHERE "spree_shipments"."order_id" = 3 AND "spree_shipments"."state" = 'ready'
   (0.1ms)  SELECT COUNT(_) FROM "spree_shipments" WHERE "spree_shipments"."order_id" = 3 AND "spree_shipments"."state" = 'pending'
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/track_inventory_levels' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'track_inventory_levels' LIMIT 1
   (0.1ms)  SELECT COUNT(_) FROM "spree_inventory_units" WHERE "spree_inventory_units"."order_id" = 3 AND "spree_inventory_units"."state" = 'backordered'
  Spree::Adjustment Load (0.2ms)  SELECT "spree_adjustments"._ FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' ORDER BY created_at ASC
  Spree::ShippingMethod Load (0.1ms)  SELECT "spree_shipping_methods".\* FROM "spree_shipping_methods" WHERE "spree_shipping_methods"."deleted_at" IS NULL AND "spree_shipping_methods"."id" = 1 LIMIT 1
  Spree::Calculator Load (0.1ms)  SELECT "spree_calculators".\* FROM "spree_calculators" WHERE "spree_calculators"."calculable_id" = 1 AND "spree_calculators"."calculable_type" = 'Spree::ShippingMethod' LIMIT 1
  SQL (0.1ms)  UPDATE "spree_adjustments" SET "amount" = 1.0 WHERE "spree_adjustments"."id" = 3
  SQL (0.1ms)  UPDATE "spree_adjustments" SET "eligible" = 't' WHERE "spree_adjustments"."id" = 3
  Spree::Adjustment Load (0.2ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."originator_type" = 'Spree::PromotionAction' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  Spree::Payment Load (0.1ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 AND "spree_payments"."state" = 'completed'
  Spree::Adjustment Load (0.2ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  SQL (0.2ms)  UPDATE "spree_orders" SET "payment_state" = 'balance_due', "shipment_state" = 'pending', "item_total" = 32.99, "adjustment_total" = 1.0, "payment_total" = 0.0, "total" = 33.99 WHERE "spree_orders"."id" = 3
   (130.7ms)  commit transaction
   (0.2ms)  SELECT COUNT(_) FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/allow_backorders' LIMIT 1
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences"._ FROM "spree_preferences" WHERE "spree_preferences"."name" = 'allow_backorders' LIMIT 1
   (0.1ms)  begin transaction
  SQL (0.2ms)  DELETE FROM "spree_payments" WHERE "spree_payments"."id" = ?  [["id", 10]](101.3ms)  commit transaction
  Spree::PaymentMethod Load (0.1ms)  SELECT "spree_payment_methods".\* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "1"]]
Redirected to http://localhost:3000/orders/R823341561/checkout/paypal_payment?payment_method_id=1
Filter chain halted as :redirect_to_paypal_express_form_if_needed rendered or redirected
Completed 302 Found in 313ms (ActiveRecord: 240.4ms)

Started GET "/orders/R823341561/checkout/paypal_payment?payment_method_id=1" for 127.0.0.1 at 2012-11-27 09:45:15 +1100
Processing by Spree::CheckoutController#paypal_payment as HTML
  Parameters: {"payment_method_id"=>"1", "order_id"=>"R823341561"}
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/allow_ssl_in_development_and_test' LIMIT 1
  Spree::Preference Exists (0.2ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/default_locale' LIMIT 1
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'default_locale' LIMIT 1
  CACHE (0.0ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/default_locale' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'default_locale' LIMIT 1
  Spree::User Load (0.3ms)  SELECT "spree_users".\* FROM "spree_users" WHERE "spree_users"."id" = 1 LIMIT 1
  Spree::Order Load (0.3ms)  SELECT "spree_orders".\* FROM "spree_orders" WHERE "spree_orders"."user_id" = 1 AND "spree_orders"."completed_at" IS NULL ORDER BY created_at ASC LIMIT 1
  Spree::Order Load (0.2ms)  SELECT "spree_orders".\* FROM "spree_orders" WHERE "spree_orders"."id" = 3 LIMIT 1
  Spree::Adjustment Load (0.3ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."adjustable_id" IN (3) ORDER BY created_at ASC
   (0.1ms)  SELECT COUNT(_) FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  Spree::LineItem Load (0.1ms)  SELECT "spree_line_items"._ FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/allow_backorders' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'allow_backorders' LIMIT 1
  Spree::Payment Load (0.1ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 AND "spree_payments"."state" = 'completed'
  Spree::Adjustment Load (0.3ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  Spree::Payment Load (0.2ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 LIMIT 1
  Spree::PaymentMethod Load (0.1ms)  SELECT "spree_payment_methods".\* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL
  CACHE (0.0ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 LIMIT 1
  Spree::Preference Load (0.2ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/billing_integration/paypal_express/review/1' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_users".\* FROM "spree_users" WHERE "spree_users"."id" = 1 LIMIT 1
   (0.2ms)  SELECT COUNT(_) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = 1 AND "spree_roles"."name" = 'admin'
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/auth_configuration/registration_step' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences"._ FROM "spree_preferences" WHERE "spree_preferences"."name" = 'registration_step' LIMIT 1
  CACHE (0.0ms)  SELECT COUNT(_) FROM "spree_line_items" WHERE "spree_line_items"."order_id" = 3
  CACHE (0.0ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/allow_backorders' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_preferences"._ FROM "spree_preferences" WHERE "spree_preferences"."name" = 'allow_backorders' LIMIT 1
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/paypal_express_configuration/paypal_express_local_confirm' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'paypal_express_local_confirm' LIMIT 1
  CACHE (0.0ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/paypal_express_configuration/paypal_express_local_confirm' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'paypal_express_local_confirm' LIMIT 1
  Spree::Preference Exists (0.1ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/logo' LIMIT 1
  Spree::Preference Load (0.1ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'logo' LIMIT 1
  CACHE (0.0ms)  SELECT 1 AS one FROM "spree_preferences" WHERE "spree_preferences"."key" = 'spree/app_configuration/logo' LIMIT 1
  CACHE (0.0ms)  SELECT "spree_preferences".\* FROM "spree_preferences" WHERE "spree_preferences"."name" = 'logo' LIMIT 1
  Spree::Variant Load (0.2ms)  SELECT "spree_variants".\* FROM "spree_variants" WHERE "spree_variants"."id" = 2 LIMIT 1
  Spree::Product Load (0.1ms)  SELECT "spree_products".\* FROM "spree_products" WHERE "spree_products"."id" = 2 LIMIT 1
  CACHE (0.0ms)  SELECT "spree_adjustments".\* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = 3 AND "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."eligible" = 't' ORDER BY created_at ASC
  CACHE (0.0ms)  SELECT "spree_payments".\* FROM "spree_payments" WHERE "spree_payments"."order_id" = 3 LIMIT 1
  Spree::ShippingMethod Load (0.2ms)  SELECT "spree_shipping_methods".\* FROM "spree_shipping_methods" WHERE "spree_shipping_methods"."deleted_at" IS NULL
  Spree::Calculator Load (0.2ms)  SELECT "spree_calculators".\* FROM "spree_calculators" WHERE "spree_calculators"."calculable_id" = 1 AND "spree_calculators"."calculable_type" = 'Spree::ShippingMethod' LIMIT 1
Completed 500 Internal Server Error in 45ms

NameError (undefined local variable or method `spree_root_url' for #Spree::CheckoutController:0xce71934):

**Comment by JDutil** [comment]
No this is a different error.  Are you using the proper branch for the version of spree that your on?  If you don't solve the issue by checking the versions your using please open a new issue with this error and your Gemfile entries for spree & spree_paypal_express.
