### ISSUE TITLE
Bundler could not find compatible versions for gem "spree_core":

### ISSUE THREAD

**Issue by guoxinghuang** [spree-contrib/spree_paypal_express#105]
MacBook-Pro:sandbox gordon$ bundle install
Updating git://github.com/spree/spree_paypal_express.git
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_paypal_express (>= 0) ruby depends on
      spree_core (~> 1.2) ruby

```
spree (>= 0) ruby depends on
  spree_core (2.0.0.beta)
```

**Comment by bolom** [comment]
I have same issue with  rails 3.2.9

**Comment by schof** [comment]
This is because the master branch of spree/spree is now version 2.0.0.beta.  We need to fix the gemsepc and create 1.3.x compatible branch and note in Versionfile.
