### ISSUE TITLE
Gateway Error: translation missing: en.the_totals_of_the_cart_item_amounts_do_not_match_order_amounts 

### ISSUE THREAD

**Issue by pavelnikolov** [spree-contrib/spree_paypal_express#106]
Hello,

I have spree 1-2-stable, and I'm using spree-paypap-express 1-2-stable branch (tried with master too but again failed). When I try to checkout an order and select PayPal express as the payment method it fails with an error: "Gateway Error: translation missing: en.the_totals_of_the_cart_item_amounts_do_not_match_order_amounts". For some reason the order total does not match cart item amounts. I spent whole weekend on that and still have no idea why this is happening.

The issue only happens if I include shipping with price > 0 (it works if I set the shipping price to 0). As soon as I change the shipping price to be a value >0 or some % it breaks. I tried with both "Shipment including VAT" true and false - same thing.

Any ideas? Is this a bug or I'm I missing something?

Pavel

**Comment by pavelnikolov** [comment]
Here are more details. I have 3 shipping options. 1 for Denmark, 1 for rest of Europe and one for outside of Europe. The problem is that in the spp extension it is hardcoded to always get the first one instead of the one matching the shipping country. This caused big problems for me.

**Comment by bolom** [comment]
I have the same issue

**Comment by JDutil** [comment]
Thanks for the report and details guys.  I'll try taking a look into this when I get a chance.  If you are able to tackle this with a pull request in the meantime before I can get to it that would be awesome, and likely get this issue resolved faster.

**Comment by bolom** [comment]
@jdutil pull submitted

**Comment by pavelnikolov** [comment]
Thanks about your effort!

**Comment by JDutil** [comment]
@pavelnikolov could you please:

```
$ bundle update spree_paypal_express
```

Then give my latest update a shot, which should resolve this issue for you.  In master as 9dd1f47110dbe26aac045441ea36d545db743d1c but for 1-2-stable which I believe your ussing is dc6bccfad3cec99bd3384de1c59d8ddbbd1f1914

**Comment by jetsgit** [comment]
@jdutil  was this fixed in Spree v.1.3.2? I just did a vanilla install + spree_tax_cloud and I got this same error.

```
Jet
```

**Comment by JDutil** [comment]
@bluehandtalking the fix for the particular error being received before is in 1-3-stable.  Are you sure your Gemfile.lock is referencing the latest commit in the 1-3-stable branch?  There could possibly be some incorrect values being passed around depending on how spree_tax_cloud ends up integrating with this extension, but I don't know of any reason why they shouldn't just work fine together.

**Comment by jetsgit** [comment]
@jdutil

Think you are right, was pulling in wrong version---that error has 
disppeared.

There is no problem with spree_tax_cloud at this point, as I have 
removed it for
this test. Side note, spree_tax_cloud now properly updates tax in cart 
if user
leaves checkout process to add or delete items in cart.

I am getting another error which I will open a separate issue on

```
 Jet
```
