### ISSUE TITLE
undefined method `preferred_cart_checkout' 

### ISSUE THREAD

**Issue by scottkf** [spree-contrib/spree_paypal_express#113]
Using Spree Gateway I have a test account setup for Stripe, and after I setup the PayPal express account and try to checkout with paypal, I get the following message on the latest from master in each branch.

``` ruby
NoMethodError (undefined method `preferred_cart_checkout' for #<Spree::Gateway::Stripe:0xbe4f7a4>):
  activemodel (3.2.10) lib/active_model/attribute_methods.rb:407:in `method_missing'
  activerecord (3.2.10) lib/active_record/attribute_methods.rb:149:in `method_missing'
  /shared/bundle/ruby/1.9.1/bundler/gems/spree-43b7c1f0faef/core/app/models/spree/gateway.rb:34:in `method_missing'
  /shared/bundle/ruby/1.9.1/bundler/gems/spree_paypal_express-573fabb7e3f5/app/controllers/spree/checkout_controller_decorator.rb:300:in `order_opts'
  /shared/bundle/ruby/1.9.1/bundler/gems/spree_paypal_express-573fabb7e3f5/app/controllers/spree/checkout_controller_decorator.rb:393:in `all_opts'
  /shared/bundle/ruby/1.9.1/bundler/gems/spree_paypal_express-573fabb7e3f5/app/controllers/spree/checkout_controller_decorator.rb:31:in `paypal_payment'
```

**Comment by JDutil** [comment]
Which branches of spree & spree_paypal_express are you using?  Have you tried to update spree_paypal_express to the latest commit for that branch?  I recently did some fixes for this that you may not be running if your out of date.

**Comment by scottkf** [comment]
Both spree and spree_paypal_express are taken from the master branches w/the latest commit from paypal being 771cb6cf3ebc. I tried manually pulling the repos to make sure as well

``` ruby
gem 'spree', :git => 'git://github.com/spree/spree.git', :branch => 'master'
gem 'spree_paypal_express', :git => 'git://github.com/spree/spree_paypal_express.git', :branch => :master
```

**Comment by JDutil** [comment]
Could you please provide a new backtrace after having updated to the latest paypal express commit.  The backtrace you've posted doesn't match up so I can't verify my fix is being run by you.  The following line in your backtrace:

```
/shared/bundle/ruby/1.9.1/bundler/gems/spree_paypal_express-573fabb7e3f5/app/controllers/spree/checkout_controller_decorator.rb:300:in `order_opts'
```

Should really look like this in the latest commit to master:
https://github.com/spree/spree_paypal_express/blob/master/app/controllers/spree/checkout_controller_decorator.rb#L301

If the version your using has order.payment_method it will cause the error your seeing.

**Comment by scottkf** [comment]
Actually, I forgot to stop/start puma, but now I get this guy:

``` ruby
NoMethodError (undefined method `state' for #<Spree::Adjustment:0xb424fe28>):
```

I'll clear the database and try again

**Comment by JDutil** [comment]
Going to close this out.  Please file a new issue if you continue to have problems with this extension.  Fair warning there could likely be issues with using Spree 2.0.x and this extension.  I only updated the gemspec to allow you to bundle the extension with edge spree.  Any backwards incompatible updates in Spree 2.0.x have not been found and/or fixed yet.  If you find any pull requests are welcome.

**Comment by scottkf** [comment]
Right, thanks!
