### ISSUE TITLE
Cannot run spree....

### ISSUE THREAD

**Issue by rezzz-dev** [spree-contrib/spree_paypal_express#12]
It seems as though when I'm using this gem, spree will not load.  Not sure why, but here's the stack trace of what's going on.

DEPRECATION WARNING: railtie_name is deprecated and has no effect. (called from class:Engine at /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/bundler/gems/spree_paypal_express-bea1aa48e008/lib/spree_paypal_express.rb:5)
/Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/railtie/configuration.rb:77:in `method_missing': undefined method`spree' for #Rails::Application::Configuration:0x00000100b9fbd0 (NoMethodError)
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/bundler/gems/spree_paypal_express-bea1aa48e008/lib/spree_paypal_express.rb:16:in `block in <class:Engine>'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/initializable.rb:25:in`instance_exec'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/initializable.rb:25:in `run'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/initializable.rb:50:in`block in run_initializers'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/initializable.rb:49:in `each'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/initializable.rb:49:in`run_initializers'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/application.rb:134:in `initialize!'
    from /Users/jason/.rvm/gems/ruby-1.9.2-p180@cvstore/gems/railties-3.0.5/lib/rails/application.rb:77:in`method_missing'
    from /Users/jason/Sites/ror/cvstore/config/environment.rb:5:in `<top (required)>'

When I comment out that gem from my Gemfile, everything loads perfectly.  Any thoughts or ideas as to what I can do to get this to work?  Thanks so much!

**Comment by runlevel5** [comment]
Again, I think you are using wrong version of spree_ppx, please make sure you run the version that is compatible, check the spree_ppx's Versionfile

**Comment by rezzz-dev** [comment]
Ok, so I looked in the Versionfile on github and see for 0.50 there's a specific ref.  How do I put that in my Gemfile?

**Comment by rezzz-dev** [comment]
When I run bundle install, it says

Using spree_paypal_express (1.0.1) from git://github.com/spree/spree_paypal_express.git (at master) 

and I'm running spree 0.50.0

I do appreciate any help as I'm totally dead in the water right now, thanks so much for your help!

**Comment by rezzz-dev** [comment]
Sorry for the newb question - I should've google'd first -- I got it and ran the bundle install and rails s started right up -- thanks so much!

**Comment by mdhany** [comment]
Hello @Rezzz-dev, where you find how to run and start right up?
