### ISSUE TITLE
CheckoutHelperDecorator no longer necessary in spree-1.3 branch.

### ISSUE THREAD

**Issue by jackkinsella** [spree-contrib/spree_paypal_express#120]
Its continued presence breaks the ability of checkout_flow customization to dynamically update the checkout_progress visual breadcrumbs because address and delivery states are hardcoded in this gem.

**Comment by skatkov** [comment]
Yeah, i'm running in to same problem here. Have to override CheckoutHelper to make it dynamic. Please remove it from gem.

**Comment by JDutil** [comment]
Updated master and 1-3-stable to resolve this.
