### ISSUE TITLE
Gateway Error: translation missing: en.callback_url_is_wrong_type_you_must_use_the_https

### ISSUE THREAD

**Issue by audioeric** [spree-contrib/spree_paypal_express#126]
Working on a fresh install of Spree and Spree_PayPal_Express and getting an issue when I go to use a production PayPal account:

When user clicks 'Save & Continue' on Payment Screen in Checkout this error appears on page:

Gateway Error: translation missing: en.callback_url_is_wrong_type_you_must_use_the_https

and there is nothing in the production.log specifically about it.

If I switch over to the test version, all works fine.

Any thoughts?

**Comment by JDutil** [comment]
You must be using https for your callbacks in production.  It is required as your passing sensitive user information back and forth with PayPal.  Once you setup SSL on your production site, and update the callback url to be your https location things will work for you.
