### ISSUE TITLE
Dummy property 'CHECKOUT FROM CART' in configuration

### ISSUE THREAD

**Issue by skatkov** [spree-contrib/spree_paypal_express#127]
![Screen Shot 2013-02-17 at 4 42 34 ](https://f.cloud.github.com/assets/544377/164195/a2c20c60-7881-11e2-9a08-0e27479e4dbf.png)
PaypalExpress configuration contains boolean property named 'CHECKOUT FROM CART' that seems  as not working. I didn't found any code that is able to do 'that this property is aimed for' and spec's also reflect my opinion:

``` ruby
# spec/controllers/checkout_controller_spec.rb
 context "paypal_checkout from cart" do
     pending 'feature not implemented'
end
```

Maybe removing this property would be good idea if feature is not implemented?

**Comment by JDutil** [comment]
The property does work for allowing users to checkout from the cart.  There currently is not any deface override to add a checkout w/paypal button to the cart page though.

**Comment by skatkov** [comment]
Can you share more info? Where can i find code that does this, so i can add Deface myself? Maybe you have issue for this with more information?

**Comment by JDutil** [comment]
You will need to add a link to the paypal payment url with the appropriate payment method id.  It'll end up looking something like this:

```
<%= link_to t(:paypal), paypal_payment_order_checkout_url(@order, :payment_method_id => @order.available_payment_methods.detect{ |method| method.type == 'Spree::BillingIntegration::PaypalExpress' }.id), :class => 'paypal-cart' %>
```

**Comment by skatkov** [comment]
Thanks for additional info.

I would expect it to go directly to paypal after clicking 'checkout with paypal'. But in my case it moves only to 'payment' page. 

This sounds correct to you?

**Comment by JDutil** [comment]
No it should take you directly to paypal.
