### ISSUE TITLE
undefined method `state_callback'

### ISSUE THREAD

**Issue by murtazajafferji** [spree-contrib/spree_paypal_express#128]
I get this error after checking out:
<code>NoMethodError in Spree::CheckoutController#paypal_confirm
undefined method `state_callback' for #Spree::CheckoutController:0x7b15be8</code>

https://github.com/spree/spree/pull/2557

**Comment by JDutil** [comment]
Fixed w/ 8290252

**Comment by MatthieuBarthel** [comment]
Sorry I posted a note on the commit instead of a comment here : 
https://github.com/spree/spree_paypal_express/commit/82902525d52b6f1ce940b2a1365da9b09b342595#commitcomment-3436303

**Comment by traels** [comment]
Please patch this in 2-0-stable also  :)

**Comment by alexmarles** [comment]
This fails in @radar 's 2-0-stable branch too
