### ISSUE TITLE
Paypal express needs to adopt the display_on attribute

### ISSUE THREAD

**Issue by matzipan** [spree-contrib/spree_paypal_express#133]
The specific error is 

```
undefined method `display_on' for #<Spree::BillingIntegration::PaypalExpress:0x000000084cec50>
```

The error seems to be triggered by something which was recently added to core: https://github.com/spree/spree/commit/f601e435321124288e057a38acd668ce65c57788

The module goes boom at `block in Spree::PaymentMethod.available spree/core/app/models/spree/payment_method.rb, line 29`  which is `(p.display_on == display_on.to_s || p.display_on.blank?)`.

So basically it goes boom because it does not implement the display_on accessor.

**Comment by radar** [comment]
Which version of Spree are you using?

Are you sure you ran the migrations again?

```
rake railties:install:migrations
rake db:migrate
```
