### ISSUE TITLE
error w latest shared / _order_details / add_paypal_details.html.erb.deface 

### ISSUE THREAD

**Issue by ghost** [spree-contrib/spree_paypal_express#137]
that's very strange checking first   which means order can have many payments

line 41 >  if order.payments.present? && order.payments.any?
then displaying   'order.payment...'  which means order has one payment ...
line 44 >  <%= t("paypal_payer_statuses.#{order.payment.source.payer_status.to_s}").capitalize %

I got an error  'undefined payment method for Order
/Users/yves/.rvm/gems/ruby-1.9.3-p392@rails32/bundler/gems/spree-e73104669d51/core/app/views/spree/shared/_order_details.html.erb where line #44 raised: 

 undefined method `payment' for #Spree::Order:0x007fa44870b7e8

I suppose this is fixed by the latest fix .... hope will be corrected in 1-3.stable soon

**Comment by fmd** [comment]
Have a look at https://github.com/spree/spree_paypal_express/pull/136; I've submitted a pull request relating to this issue

**Comment by AlexEscalante** [comment]
I confirm this issue.

**Comment by JDutil** [comment]
Should be fixed by #136
