### ISSUE TITLE
1-3-stable, undefined method `payment'

### ISSUE THREAD

**Issue by pfac** [spree-contrib/spree_paypal_express#139]
**spree** + **spree_auth_devise** + **spree_paypal_express**

Followed the README to add this gem in the last stable version, everything went well on the Paypal side, but got _undefined method `payment'_.

Not much setup needed to replicate this in other machines: just added a product, a US shipping method, the paypal payment method (as explained in the [README](https://github.com/spree/spree_paypal_express/blob/1-3-stable/README.md)), picked some items and followed through the checkout.

**Comment by msevestre** [comment]
That's the same as #84

**Comment by pfac** [comment]
Sorry, didn't come up in search. Closing & following #84
