### ISSUE TITLE
Payment confirm fails if state abbr has different casing

### ISSUE THREAD

**Issue by bazlo** [spree-contrib/spree_paypal_express#14]
Payment confirm will fail if e.g.

spree state abbr = 'QLD'

paypal state = 'Qld'

works fine if paypal state is full name e.g. 'Queensland' or if paypal has same casing as spree 'QLD'

I think the search needs to be case insensitive somehow.

[https://github.com/spree/spree_paypal_express/blob/master/app/controllers/checkout_controller_decorator.rb#L82](https://github.com/spree/spree_paypal_express/blob/master/app/controllers/checkout_controller_decorator.rb#L82)

NOTE: This is only a problem for paypal accounts who have not updated their shipping address for awhile, Paypal now forces the format of the state with a dropdown. which is good.

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.

**Comment by RohanM** [comment]
I encountered this issue, again with Australian state names. I have a fix on a fork in this commit:

https://github.com/eaterprises/spree_paypal_express/commit/d2f38e5068c4b6979c2af7f64caca9e1df50de89

**Comment by radar** [comment]
@RohanM: Just a note: we have a new paypal express extension at https://github.com/radar/better_spree_paypal_express. I would be super keen if your team could evaluate that and see if it meets your needs. Would you be able to do that?
