### ISSUE TITLE
Installation Issues - Spree 1.3.2

### ISSUE THREAD

**Issue by ziyan-junaideen** [spree-contrib/spree_paypal_express#142]
I am attempting to install paypal express checkout, I added the information in the Gemfile and ran `bundle install` where it ended up here.
`
  gem 'spree', '1.3.2'
  gem 'spree_gateway', :github => 'spree/spree_gateway', :branch => '1-3-stable'
  gem 'spree_auth_devise', :github => 'spree/spree_auth_devise', :branch => '1-3-stable'
  gem 'spree_static_content', :github => 'spree/spree_static_content', :branch => '1-3-stable'
`

This is the error:

`Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_paypal_express (>= 0) ruby depends on
      spree_core (~> 2.0.0.beta) ruby
    spree_static_content (>= 0) ruby depends on
      spree_core (1.3.2)
`

I am very new to Ruby/Rails, but I believe that should it support v2 of spree_core, it should support 1.3.2. Am I not?

The gemfile specifically asks for 1.3.2, would removing it resolve the issue?

What else information should I provide for more information?

If this is not a bug, how would it be possible to fix this.

**Comment by JDutil** [comment]
Spree extensions use a [Versionfile](https://github.com/spree/spree_paypal_express/blob/master/Versionfile) to notify people of which versions of spree you can use with the extension.

In this case the Versionfile says that for Spree 1.3.x to use the 1-3-stable branch.

So in your gemfile you should be defining the extension like so:

```
gem 'spree_paypal_express', github: 'spree/spree_paypal_express', branch: '1-3-stable'
```

For more information on spree extensions you can read the guides http://guides.spreecommerce.com/extensions.html

**Comment by ziyan-junaideen** [comment]
Thanks, it worked... my bad, I saw a hint on the Readme file, sorry!
