### ISSUE TITLE
Development guidelines

### ISSUE THREAD

**Issue by szajbus** [spree-contrib/spree_paypal_express#149]
Hi,
At the moment this extension is broken and doesn't work with Spree 2.0.x due to shipments logic changes in 2.0, so I believe there should be no `2-0-stable` branch at all yet.

I'd like to to help making it 2.0-compatible. Are there any development guidelines for this extension or all spree extensions in general? 

Should I commit fixes to `master` branch and they will be later mergen into `*-stable` braches?

**Comment by JDutil** [comment]
Yes I would develop within a feature branch off of master, which would get merged to master and then cherry-picked to appropriate stable branches.

Heres a link to the developer contributing guidelines http://guides.spreecommerce.com/developer/contributing.html on the guides site.

**Comment by JDutil** [comment]
Going to close as this is more a question than an issue.

**Comment by szajbus** [comment]
@jdutil Thanks. Shame on me, I should have read that first.
