### ISSUE TITLE
Rails 4 without protected_attributes gem will fail on attr_accessible 

### ISSUE THREAD

**Issue by dot79** [spree-contrib/spree_paypal_express#156]
Is supposed to be handled a rails4 branch?
Thanks

**Comment by fresh2nd** [comment]
I have the same issue, this should be updated to use the new rails4 way to manage this on controllers and not with rpotected_attributes

**Comment by msevestre** [comment]
spree_paypal_express gem will in a forseable future not be maintain anymore.
I would strongly advise you to try the
better_spree_paypalhttps://github.com/radar/better_spree_paypal_expressextension

Hope that helps

**Comment by radar** [comment]
Yes, as @msevestre: Please do not use this extension. Use my extension instead.

**Comment by eevee** [comment]
It would be pretty helpful if this advice appeared, say, in the README or repo description, rather than only in a closed ticket.
