### ISSUE TITLE
error when order is completed

### ISSUE THREAD

**Issue by NARKOZ** [spree-contrib/spree_paypal_express#159]
When order completed the following error raises:

```
undefined method `payment' for #<Spree::Order:0x007fe301a0b2c0>
```

It seems related to deface https://github.com/spree/spree_paypal_express/blob/master/app/overrides/spree/shared/_order_details/add_paypal_details.html.erb.deface because when I remove `<div class="payment-info">` from `app/views/spree/shared/_order_details.html.erb` the error goes. 
There is no error when I copy-paste contents of `add_paypal_details.html.erb` to `_order_details.html.erb`.

**Comment by radar** [comment]
Hi @NARKOZ, could you please do me a favour and attempt to use the better_spree_paypal_express extension which I mention here? https://groups.google.com/forum/#!topic/spree-user/zXSL3Y1GAUw. My extension should be a replacement for spree's spree_paypal_express extension, but I need some beta testers to give it a run through. If you could do that, then that'd be mighty helpful.

Thanks!
