### ISSUE TITLE
Error confirming payment method, undefined method `process_coupon_code'

### ISSUE THREAD

**Issue by matteofuzz** [spree-contrib/spree_paypal_express#16]
Spree 0.70.1, error after confirm payment, with any payment method, also with check.

NoMethodError in CheckoutController#update

undefined method `process_coupon_code' for #Order:0x0000012f88d788

**Comment by patrickmcelwee** [comment]
+1 This is still an issue, running Spree 0.70.4

I applied this patch, and it seems to have fixed the issue for me.
