### ISSUE TITLE
bundle exec rails g spree_paypal_express:install

### ISSUE THREAD

**Issue by jmoon90** [spree-contrib/spree_paypal_express#164]
Hi

I followed the instruction for the spree paypal express gem. However when I bundle exec rails ... I get the following error. Could you help me solve this problem?

/Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activemodel-4.0.0/lib/active_model/deprecated_mass_assignment_security.rb:14:in `attr_accessible':`attr_accessible`is extracted out of Rails into a gem. Please use new recommended protection model for params(strong_parameters) or add`protected_attributes`to your Gemfile to use old one. (RuntimeError)
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree_paypal_express-a74f4104cc1a/app/models/spree/billing_integration/paypal_express_base.rb:11:in`class:PaypalExpressBase'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree_paypal_express-a74f4104cc1a/app/models/spree/billing_integration/paypal_express_base.rb:1:in `<top (required)>'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in`load'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `block in load_file'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:615:in`new_constants_in'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:422:in `load_file'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:323:in`require_or_load'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:462:in `load_missing_constant'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:183:in`const_missing'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree_paypal_express-a74f4104cc1a/app/models/spree/billing_integration/paypal_express.rb:1:in `<top (required)>'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in`load'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `block in load_file'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:615:in`new_constants_in'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:422:in `load_file'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:323:in`require_or_load'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:462:in `load_missing_constant'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:183:in`const_missing'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/bundler/gems/spree_paypal_express-a74f4104cc1a/lib/spree_paypal_express/engine.rb:25:in `block in <class:Engine>'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:30:in`instance_exec'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:183:in`block (2 levels) in each_strongly_connected_component'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:182:in`block in each_strongly_connected_component'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in`each_strongly_connected_component'
    from /Users/sungmoon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/initializable.rb:54:in`run_initializers'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /users/sungmoon/rails_project/cart/config/environment.rb:5:in `<top (required)>'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/polyglot-0.3.3/lib/polyglot.rb:63:in`require'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in`block in require'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in`require'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/application.rb:189:in `require_environment!'
    from /Users/sungmoon/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:45:in`<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in`<main>'

**Comment by radar** [comment]
It looks like you're trying to use Rails 4 with this extension. Rails 4 is currently not supported by this extension.

---

I would recommend checking out my [better_spree_paypal_express](https://github.com/radar/better_spree_paypal_express) extension.
