### ISSUE TITLE
Shipping Address overridden

### ISSUE THREAD

**Issue by christoph-buente** [spree-contrib/spree_paypal_express#169]
When a customer defines different billing and shipping addresses and chooses to pay with paypal express it seems, that the first and last name of the shipping address are overridden with the name from the billing address. We had some confusion with this, cause parcels returned to us cause the billing person could not been found at the shipping address.

Can this issue be reproduced somehow? I have seen the paypal_confirm method in the checkout_controller_decorator, which seems to create a new shipping address when the no_shipping option is not set. (Double negation tends to twist my mind).

Would be great to get some help on this.

**Comment by radar** [comment]
Could you please try out my extension radar/better_spree_paypal_express? This extension is no longer maintained

**Comment by christoph-buente** [comment]
I'm still on 1.3.3, so i guess it's not gonna work.

**Comment by radar** [comment]
@christoph-buente If you upgrade to 1.3.4 it will work. I've just created a 1-3-stable branch for it today.

**Comment by christoph-buente** [comment]
Thx a bunch. I'm gonna upgrade to 1.3.4 and check it out.

**Comment by christoph-buente** [comment]
I upgraded our shop to 1-3-4 with the better_spree_paypal_express and it works like a charm. Thx a billion.

**Comment by radar** [comment]
@christoph-buente Great to hear :)
