### ISSUE TITLE
Version in Documentation

### ISSUE THREAD

**Issue by cleverlemming** [spree-contrib/spree_paypal_express#19]
documentation says: "The master branch of this repo is currently for Spree 0.40.3 and later..."

gemspec says: "add_dependency('spree_core', '>=0.70.1')"

**Comment by schof** [comment]
The `README` is out of date (and not the best way to track versioning.)  Are you using it in a specific version of Spree?  If you are, we can update the `Versionfile` with the SHA that works for whatever version you're on.  

See the [Extension Guides](http://guides.spreecommerce.com/creating_extensions.html#versionfile) for more info on how we can do this.  TIA for your help.

**Comment by GeekOnCoffee** [comment]
This README has been updated since this ticket was created and no longer includes version information.
