### ISSUE TITLE
checkout_controller_decorator will ignore additional attributes

### ISSUE THREAD

**Issue by zecke** [spree-contrib/spree_paypal_express#20]
In our shop we have have an additional field to accept the Terms/Conditions and with this extension the additional attribute will not be saved. We have worked around this by saving one more hard-coded attribute.

https://gitorious.org/sysmocom-spreecommerce/spree_paypal_express/commit/8dc2c34ae9790e1968af88e4551a6712bad4436a

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
