### ISSUE TITLE
PayPal overrides/loses address information

### ISSUE THREAD

**Issue by zecke** [spree-contrib/spree_paypal_express#21]
When a payment returns from PayPal the shipping address will be replaced and this creates several problems:

1.) Any additional address information is lost. In our case it is the EUVAT id of the place we are shipping to...
2.) For PayPal to work for US customers we need them to enter the 'State' and in spree config we require the state, when an order from some European countries return the State is nil.. and then the Address fails to validate and the checkout does not complete.

We have worked around this by creating a 'Paypal Address' and setting the State to N/A in case it does not return from PayPal.

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
