### ISSUE TITLE
Credit a customer does not work

### ISSUE THREAD

**Issue by zecke** [spree-contrib/spree_paypal_express#25]
1.) User completes purchase
2.) E.g. shipping cost gets reduced/locked

3.) Capture to capture payment... will capture the full amount...
4.) Pressing 'Credit' will fail with PayPal saying that credit must be positive...

What I would like:
Adjust @order.payment.amount to the order.total_amount before capture (this will allow to charge up to 115%), fix credit...

**Comment by GeekOnCoffee** [comment]
Closing due to age. Feel free to comment if it's still an issue, and we'll reopen.
