### ISSUE TITLE
Payment process is not a true 'transaction'

### ISSUE THREAD

**Issue by zecke** [spree-contrib/spree_paypal_express#27]
I can only describe the symptoms here:

Setup:
1) Paypal extension is configured to not auto capture
2) Review is not ticked
3) Currency is in EUR
4) Live environment

Purchase
1.) Customer gets to paypal
2.) Returns to https://shop/orders/R666666666/checkout/paypal_confirm?payment_method_id=6&token=TOK&PayerID=FOO
     Gets a "504 Gateway Timeout"
3.) Customer gets a Order Confirmation Email
4.) Payment is not received/known to paypal

Database:
1.) PaypalAccount has a record for this purchase
# <PaypalAccount id: 666, email: "customer@foo.com", payer_id: "ID", payer_country: "NA", payer_status: "verified">
# <Payment id: 666, order_id: 666, created_at: "2011-11-28 10:12:55", updated_at: "2011-11-28 10:12:55", amount: #<BigDecimal:some number>, source_id: 666, source_type: "PaypalAccount", payment_method_id: 6, state: "pending", response_code: "Success", avs_response: nil>

So apparently the order is confirmed before it is confirmed with paypal. My logfile configuration didn't allow me to see if the 504 was generated by my frontend (cherokee), or by spree (e.g. processing timeout) or by paypal.

Any idea of where this could have gone wrong? Is there any code that starts a timeout?

**Comment by BDQ** [comment]
Cannot replicate closing for now.
