### ISSUE TITLE
rake error

### ISSUE THREAD

**Issue by dhawalshah** [spree-contrib/spree_paypal_express#30]
Getting a rake error when trying to do "rake spree_paypal_express:install" in the terminal. The trace shows that the FileUtilz.mirror_files method is not found. Is there a specific ref to use for the extension when using Spree 0.70.3 or is just pulling from master ok? Please help me resolve this issue. 

Cheers!

**Comment by mcgoooo** [comment]
reverted the change in the bottom of the this commit, seems to of fixed it, maybe . it's in lib/tasks/spree_paypal_express.rake

https://github.com/spree/spree_paypal_express/commit/3a1fcf17712ce9615816c93f048da553407bec1c#lib/tasks/spree_paypal_express.rake

**Comment by mcgoooo** [comment]
i reverted to the last commit on https://github.com/spree/spree_paypal_express/commits/master  from october 8 and at least the rake tasks work, now need to look whether the full thing works

**Comment by mcgoooo** [comment]
no success, experiencing the same issues as dhawalshah.
