### ISSUE TITLE
paypal_express_local_confirm preference not defined

### ISSUE THREAD

**Issue by chrise86** [spree-contrib/spree_paypal_express#31]
Getting the following when checking out:

`NoMethodError in Spree::CheckoutController#paypal_payment`

`paypal_express_local_confirm preference not defined`

Using Rails 3.1.3 and Spree 1.0.0.rc3 --edge

**Comment by chrise86** [comment]
Added an initializer containing:

`rubySpree::AppConfiguration.class_eval do
  preference :paypal_express_local_confirm, :boolean, :default => true
end`

**Comment by lucapette** [comment]
@chrise86 I've used the same fix but are we sure it is the right way of doing it. Probably the extension should do that. Don't you think?

**Comment by chrise86** [comment]
@lucapette yes definitely, if it is something that is essential to the extension then it should be offered as an option in the configuration or backend preferences as standard...

**Comment by lucapette** [comment]
@chrise86 If you're agree with me you could be re-open the issue. It's a good way of keeping on eye on the problem.

**Comment by LBRapid** [comment]
This preference can now be set using Spree::PaypalExpress::Config[:paypal_express_local_confirm]. Defaults to true unless  set in an initializer or elsewhere.

**Comment by lucapette** [comment]
@LBRapid thank you very much!
