### ISSUE TITLE
uninitialized constant PaypalAccount 

### ISSUE THREAD

**Issue by cnight** [spree-contrib/spree_paypal_express#34]
With spree 1.0.0, checking out with paypal express works but trying to access the order payments in the admin leads to an error:  uninitialized constant PaypalAccount on line 16 of spree_core-1.0.0/app/views/spree/admin/payments/_list.html.erb 

13:       <td><%= link_to payment_method_name(payment), admin_order_payment_path(@order, payment) %></td>
14:       <td><%= t(payment.state, :scope => :payment_states, :default => payment.state.capitalize) %></td>
15:       <td>
16:         <% payment.actions.each do |action| %>
17:           <%= button_to t(action), fire_admin_order_payment_path(@order, payment, :e => action), :method => :put %>
18:         <% end %>
19:       </td>

Tracked this back to the paypal_finish method in the checkout_controller_decorator, the source_type field is being set to an incorrectly name-spaced class name missing the Spree:: module prefix.

**Comment by LBRapid** [comment]
This should be okay now. Kind of funny I saw this message instantly after merging in a pull request that fixes the reported issue.

**Comment by cnight** [comment]
OK, thanks!

On Tue, Feb 14, 2012 at 9:40 PM, John Dyer
reply@reply.github.com
wrote:

**Comment by cnight** [comment]
I get an error on the return URL's on this one, it is trying to go to
/spree/orders/ instead of just /orders/

**Comment by LBRapid** [comment]
Pushed a fix. Let me know how it works out. I'll have time to look at this tomorrow if there are remaining problems.

**Comment by cnight** [comment]
Checkout works, but the callback URL still says /spree/ (line 272),
this seems like an error too.

On Tue, Feb 14, 2012 at 10:10 PM, John Dyer
reply@reply.github.com
wrote:

**Comment by cnight** [comment]
Hi John, I have submitted a pull request to fix this and also fix
another namespace error on Spree::Core::GatewayError.
