### ISSUE TITLE
Can spree_paypal_express deal with parallel payments?

### ISSUE THREAD

**Issue by digitalWestie** [spree-contrib/spree_paypal_express#51]
Not so much of an issue but just the question. Is it possible to pay more than one recipient at once?

**Comment by radar** [comment]
I don't think that this would be possible. Does PayPal itself even support such a feature?

**Comment by jumph4x** [comment]
@radar: No, not to my knowledge.

@digitalWestie: Are you looking for revenue sharing?

**Comment by digitalWestie** [comment]
@jumph4x, yes that's right. I understand it's a bit of an edge case.

Yes, parallel payment is available under paypal adaptive and paypal express. I recently discovered a gem that covers this: https://gist.github.com/2490428 - was just wondering if there was some similar functionality here.
