### ISSUE TITLE
paypal_express_uk.rb requires attr_accessible :preferred_allow_guest_checkout

### ISSUE THREAD

**Issue by simonsparks** [spree-contrib/spree_paypal_express#62]
To avoid MassAssignment errors, the list of `attr_accessible` fields in /app/models/spree/billing_integration/paypal_express_uk.rb must also include `:preferred_allow_guest_checkout` as it does in the regular paypal_express.rb file.

**Comment by JDutil** [comment]
This has been fixed by 26da5770907c396aa8e9d16d5e7685311e3b7240
