### ISSUE TITLE
Incompatability of credit method between Spree 1.1.1 and PaypalExpress

### ISSUE THREAD

**Issue by cwise** [spree-contrib/spree_paypal_express#67]
Long story short, we've run into an issue attempting to process Paypal credits through the admin interface. 

When attempting to fire the credit, we find that the payment method (Spree::BillingIntegration::PaypalExpress) doesn't have a credit method that the payment/processing class in Spree is looking for:

/gems/spree_core-1.1.1/app/models/spree/payment/processing.rb:76:in `block in credit!'

That particular method within Spree was is expecting the payment method to implement credit. I'm pretty sure that it used to happen through the payment source (PaypalAccount).

def credit(amount)
      return if amount > credit_allowed
      started_processing!
      source.credit(self, amount)
    end
end

I don't have the time to delve into this right now (as I am having to manually process credits on the console) but I'm pretty sure something might be been missed in the refactoring to payment/processing.rb.

**Comment by radar** [comment]
Do you have a way that we can reproduce this problem?

**Comment by BDQ** [comment]
Credits are working for on 1-1-stable and master right now.
