### ISSUE TITLE
Bundler could not find compatible versions for gem "spree_core"

### ISSUE THREAD

**Issue by murtazajafferji** [spree-contrib/spree_paypal_express#79]
I just updated my Gemfile from:
<code>gem 'spree', '1.1.2.rc1'</code>
to:
<code>gem 'spree', :git => "git://github.com/spree/spree.git", :branch => '1-2-stable'</code>

and now I'm getting this error when I run <code>bundle update</code>:

<code>Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_social (>= 0) x86-mingw32 depends on
      spree_core (~> 1.1.0) x86-mingw32

```
spree_paypal_express (>= 0) x86-mingw32 depends on
  spree_core (1.2.0)</code>
```

**Comment by JDutil** [comment]
Please see https://github.com/spree/spree_social/issues/47

**Comment by murtazajafferji** [comment]
I have decided to revert back to <code>gem 'spree', '1.1.2.rc1'</code> until Spree 1.2 is fully supported. Thanks.
