### ISSUE TITLE
Payment Methods are registered incorrectly

### ISSUE THREAD

**Issue by jsqu99** [spree-contrib/spree_paypal_express#81]
Attempting to start a rails server using spree 1.2 yields:

/Users/jeffsquires/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree_paypal_express-28c925e1f1aa/lib/spree_paypal_express/engine.rb:24:in `block in <class:Engine>': undefined method`+' for nil:NilClass (NoMethodError)

Changing the section starting at: https://github.com/spree/spree_paypal_express/blob/master/lib/spree_paypal_express/engine.rb#L23

to:

```
initializer "spree_paypal_express.register.payment_methods" do |app|
  app.config.spree.payment_methods += [
    Spree::BillingIntegration::PaypalExpress,
    Spree::BillingIntegration::PaypalExpressUk
  ]
end
```

Seems to fix this issue.

Pull request coming.

**Comment by tomash** [comment]
could this be merged also to 1-1 branch? because i have the same issue with spree 1.1.2.
