### ISSUE TITLE
1-1-stable, :review breaks collection of payment

### ISSUE THREAD

**Issue by jumph4x** [spree-contrib/spree_paypal_express#84]
For the 1-1-stable branch, enabling :review breaks collection of payment.

Order moves to :complete, but no actual payment is collected from the user. Just deployed 1-1-3 to production, ask me how I know...

Disabling :review moves things along nicely. Don't forget to re-enter password.

**Comment by runlevel5** [comment]
@jumph4x please submit a patch, I'll review for you

**Comment by geermc4** [comment]
@jumph4x is this what you where seeing `NoMethodError: undefined method 'payment' for #<Spree::Order:0x00000006c1fb28>`, if so, how did you fixed it, removing the Review check didn't do it for me.

**Comment by jumph4x** [comment]
@geermc4 not the same...

**Comment by geermc4** [comment]
@jumph4x yup, your right, that method is gone now, https://github.com/spree/spree/commit/3d0fa4ff434569ff8491aba690fde87e577ec19c

**Comment by fmd** [comment]
I am also getting this issue on 1-3-stable, even after https://github.com/spree/spree_paypal_express/commit/b0173f73e750d016e0533bf7b3f4e2cf7fe68bb7

**Comment by fmd** [comment]
I have put in a pull request that fixes this issue for me on 1-3-stable.

https://github.com/spree/spree_paypal_express/pull/136
