### ISSUE TITLE
Setting Auto Capture = true doesn't auto capture and causes "Transaction ID is invalid." in Admin UI

### ISSUE THREAD

**Issue by joemsak** [spree-contrib/spree_paypal_express#88]
Please read the steps linked in the first comment for full story on this issue

**Comment by joemsak** [comment]
Steps to reproduce outlined here:

https://github.com/spree/spree/issues/2102#issuecomment-9589331

**Comment by joemsak** [comment]
Update:

It turns out this is likely an issue when dealing in foreign currencies.

This can be resolved by setting this setting in your Paypal Store (Sandbox test or otherwise)

It should be noted that we are using EUR. We have configured the Payment Method to use EUR and the paypal store is in EUR. We are also only using a Paypal Sandbox Test Store as of this comment. We haven't yet been in production.

```
Profile > My Selling Tools > Payment Receiving Preferences >
```

```
Block payments sent to me in a currency I do not hold:
 [ ] Yes
 [x] No, accept them and convert them to U.S. Dollars
 [ ] Ask Me
```

HOWEVER:

This still leaves the Shipment Status at "Pending" and to make the Shipment Status switch to "Ready" I must log in to /admin/orders, Click on the Order, go to "Shipments" click "Edit" on my shipment, then click "Update" on the resulting form.

I know that our client will not accept this

**Comment by neotericdesign** [comment]
Could someone remind us what the method is that needs to be called in order to make the Shipment status go to Ready? Thanks!

**Comment by JDutil** [comment]
Does the product being ordered have enough quantity on hand to fulfill the order?  If there is insufficient stock then the shipment will remain in a pending state.

**Comment by JDutil** [comment]
As mentioned on https://github.com/spree/spree/issues/2102 this issue has been resolved.
