### ISSUE TITLE
Disable the paypal button

### ISSUE THREAD

**Issue by jsqu99** [spree-contrib/spree_paypal_express#92]
I believe we should force the user to use the 'save and continue' button instead of the paypal button.

The reason for this is two-fold:
- propagate the coupon code to spree (we currently ignore the coupon code if they use the button)
- make the UI behave the same way for all payment methods

Pull request coming

**Comment by msevestre** [comment]
+1 for that

**Comment by JDutil** [comment]
Fixed with ebecca518b834b00f65466e045d7aacc18137c8b
